(function(){'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,g){a!=Array.prototype&&a!=Object.prototype&&(a[d]=g.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,d){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:d})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(g){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(g||"")+"_"+d++,g)}var d=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,d){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var g=0,e={next:function(){if(g<a.length){var k=g++;return{value:d(k,a[k]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(a,d,g,e){if(d){g=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var k=a[e];k in g||(g[k]={});g=g[k]}a=a[a.length-1];e=g[a];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,g,e){g=null!=g?g:function(a){return a};var d=[],l="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof l){a=l.call(a);for(var n=0;!(l=a.next()).done;)d.push(g.call(e,l.value,n++))}else for(l=a.length,n=0;n<l;n++)d.push(g.call(e,a[n],n));return d}},"es6","es3");$jscomp.owns=function(a,d){return Object.prototype.hasOwnProperty.call(a,d)};
$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var d=[],e;for(e in a)$jscomp.owns(a,e)&&d.push(a[e]);return d}},"es8","es3");$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},d={};try{return d.__proto__=a,d.a}catch(g){}return!1};$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,d){a.__proto__=d;if(a.__proto__!==d)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.polyfill("Object.setPrototypeOf",function(a){return a||$jscomp.setPrototypeOf},"es6","es5");$jscomp.findInternal=function(a,d,g){a instanceof String&&(a=String(a));for(var e=a.length,k=0;k<e;k++){var l=a[k];if(d.call(g,l,k,a))return{i:k,v:l}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.findIndex",function(a){return a?a:function(a,g){return $jscomp.findInternal(this,a,g).i}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,g,e){var d=this.length||0;0>g&&(g=Math.max(0,d+g));if(null==e||e>d)e=d;e=Number(e);0>e&&(e=Math.max(0,d+e));for(g=Number(g||0);g<e;g++)this[g]=a;return this}},"es6","es3");$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},d=Object.create(new $jscomp.global.Proxy(a,{get:function(g,e,k){return g==a&&"q"==e&&k==d}}));return!0===d.q}catch(g){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;
$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.makeIterator=function(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill("WeakMap",function(a){function d(){if(!a||!Object.seal)return!1;try{var y=Object.seal({}),e=Object.seal({}),d=new a([[y,2],[e,3]]);if(2!=d.get(y)||3!=d.get(e))return!1;d.delete(y);d.set(e,4);return!d.has(y)&&4==d.get(e)}catch(E){return!1}}function g(){}function e(a){if(!$jscomp.owns(a,l)){var e=new g;$jscomp.defineProperty(a,l,{value:e})}}function k(a){var y=Object[a];y&&(Object[a]=function(a){if(a instanceof g)return a;e(a);return y(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&
$jscomp.ES6_CONFORMANCE)return a}else if(d())return a;var l="$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var n=0,w=function(a){this.id_=(n+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var e;!(e=a.next()).done;)e=e.value,this.set(e[0],e[1])}};w.prototype.set=function(a,d){e(a);if(!$jscomp.owns(a,l))throw Error("WeakMap key fail: "+a);a[l][this.id_]=d;return this};w.prototype.get=function(a){return $jscomp.owns(a,l)?a[l][this.id_]:void 0};w.prototype.has=
function(a){return $jscomp.owns(a,l)&&$jscomp.owns(a[l],this.id_)};w.prototype.delete=function(a){return $jscomp.owns(a,l)&&$jscomp.owns(a[l],this.id_)?delete a[l][this.id_]:!1};return w},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function d(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var e=Object.seal({x:4}),d=new a($jscomp.makeIterator([[e,"s"]]));if("s"!=d.get(e)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var g=d.entries(),k=g.next();if(k.done||k.value[0]!=e||"s"!=k.value[1])return!1;k=g.next();return k.done||4!=k.value[0].x||"t"!=k.value[1]||!g.next().done?!1:!0}catch(F){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(d())return a;$jscomp.initSymbolIterator();var g=new WeakMap,e=function(a){this.data_={};this.head_=n();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var e;!(e=a.next()).done;)e=e.value,this.set(e[0],e[1])}};e.prototype.set=function(a,e){a=0===a?0:a;var d=k(this,a);d.list||(d.list=this.data_[d.id]=[]);d.entry?d.entry.value=e:(d.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:e},d.list.push(d.entry),this.head_.previous.next=d.entry,this.head_.previous=d.entry,this.size++);return this};e.prototype.delete=function(a){a=k(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=n();this.size=0};e.prototype.has=function(a){return!!k(this,a).entry};
e.prototype.get=function(a){return(a=k(this,a).entry)&&a.value};e.prototype.entries=function(){return l(this,function(a){return[a.key,a.value]})};e.prototype.keys=function(){return l(this,function(a){return a.key})};e.prototype.values=function(){return l(this,function(a){return a.value})};e.prototype.forEach=function(a,e){for(var d=this.entries(),g;!(g=d.next()).done;)g=g.value,a.call(e,g[1],g[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var k=function(a,e){var d=e&&typeof e;"object"==
d||"function"==d?g.has(e)?d=g.get(e):(d=""+ ++w,g.set(e,d)):d="p_"+e;var k=a.data_[d];if(k&&$jscomp.owns(a.data_,d))for(a=0;a<k.length;a++){var l=k[a];if(e!==e&&l.key!==l.key||e===l.key)return{id:d,list:k,index:a,entry:l}}return{id:d,list:k,index:-1,entry:void 0}},l=function(a,e){var d=a.head_;return $jscomp.iteratorPrototype(function(){if(d){for(;d.head!=a.head_;)d=d.previous;for(;d.next!=d.head;)return d=d.next,{done:!1,value:e(d)};d=null}return{done:!0,value:void 0}})},n=function(){var a={};return a.previous=
a.next=a.head=a},w=0;return e},"es6","es3");$jscomp.assign="function"==typeof Object.assign?Object.assign:function(a,d){for(var g=1;g<arguments.length;g++){var e=arguments[g];if(e)for(var k in e)$jscomp.owns(e,k)&&(a[k]=e[k])}return a};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");
(function(a){function d(e){if(g[e])return g[e].exports;var k=g[e]={i:e,l:!1,exports:{}};a[e].call(k.exports,k,k.exports,d);k.l=!0;return k.exports}var g={};d.m=a;d.c=g;d.d=function(a,g,l){d.o(a,g)||Object.defineProperty(a,g,{enumerable:!0,get:l})};d.r=function(a){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})};d.t=function(a,g){g&1&&(a=d(a));if(g&8||g&4&&"object"===typeof a&&a&&a.__esModule)return a;
var e=Object.create(null);d.r(e);Object.defineProperty(e,"default",{enumerable:!0,value:a});if(g&2&&"string"!=typeof a)for(var k in a)d.d(e,k,function(d){return a[d]}.bind(null,k));return e};d.n=function(a){var e=a&&a.__esModule?function(){return a["default"]}:function(){return a};d.d(e,"a",e);return e};d.o=function(a,d){return Object.prototype.hasOwnProperty.call(a,d)};d.p="";return d(d.s=4)})([function(a,d,g){a.exports={chartContainer:"_3Kp5o7RruKidI1ceIQDvrE",chartTitle:"_2a8wANmODgPnccDUldcOqD",
previewWrapper:"T_lXQnUaSe4e8dEJCGe_l",chartWrapper:"_3jqLxlEZqRswFEbI3Tilqk",layer:"_15bywRdIlzdk53NEYr9Gl3",buttonsWrapper:"cj9mCMN3rkeSucQueDpUW",nightMode:"mKtZwWmFkxBh9DH71crEU",modeLink:"_2cfANduKwNkCL4yvaEX7Bo",modeLinkWrapper:"_3-azWK_-3-MDhKEhNLVPOl",buttonWrapper:"_1asqrW83RplQ0RdACo-zLX"}},function(a,d,g){a.exports={active:"_3PbXgXpXDhNxxyXkhkmECK",buttonLabelCircle:"wueb78C8VRaqMEut8wDN4",buttonLabelIcon:"_3Ol41HhAZvwbofm0lIQ-0X",buttonWrapper:"_1Y0hOJE83-BbA0xw2Wq8c",buttonText:"_1HVhCRI8qehoiWhLWCLL4y",
buttonLabel:"_3DUzAL97qk3vCuZv5ZTGeT"}},function(a,d,g){a.exports={preview:"_1RjnR8nQMSev6CXuRjLUwX",previewBase:"_2nReggaapMZ8dD5AvH4RuB",previewWindow:"QVH7P9eP5Y6QtlKykf0Og"}},function(a,d,g){a.exports={modeLink:"aEVHLv-4Qn_9F0erKQyj3",modeLinkWrapper:"_1ZVbvXUccCD7RJGn9JaTai"}},function(a,d,g){function e(a,b){if(null==a)return{};if(null==a)var c={};else{c={};var h=Object.keys(a),p;for(p=0;p<h.length;p++){var d=h[p];0<=b.indexOf(d)||(c[d]=a[d])}}if(Object.getOwnPropertySymbols)for(p=Object.getOwnPropertySymbols(a),
d=0;d<p.length;d++)h=p[d],0<=b.indexOf(h)||Object.prototype.propertyIsEnumerable.call(a,h)&&(c[h]=a[h]);return c}function k(a){for(var b=1;b<arguments.length;b++){var c=null!=arguments[b]?arguments[b]:{},h=Object.keys(c);"function"===typeof Object.getOwnPropertySymbols&&(h=h.concat(Object.getOwnPropertySymbols(c).filter(function(b){return Object.getOwnPropertyDescriptor(c,b).enumerable})));h.forEach(function(b){l(a,b,c[b])})}return a}function l(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,
configurable:!0,writable:!0}):a[b]=c;return a}function n(a){if(Array.isArray(a)){var b=0;for(var c=Array(a.length);b<a.length;b++)c[b]=a[b];b=c}else b=void 0;b||(b=Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a)?Array.from(a):void 0);if(!(a=b))throw new TypeError("Invalid attempt to spread non-iterable instance");return a}function w(a){for(var b=1;b<arguments.length;b++){var c=null!=arguments[b]?arguments[b]:{},h=Object.keys(c);"function"===typeof Object.getOwnPropertySymbols&&
(h=h.concat(Object.getOwnPropertySymbols(c).filter(function(b){return Object.getOwnPropertyDescriptor(c,b).enumerable})));h.forEach(function(b){r(a,b,c[b])})}return a}function y(a,b){for(var c=0;c<b.length;c++){var h=b[c];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function ea(a,b,c){b&&y(a.prototype,b);c&&y(a,c);return a}function r(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;
return a}function E(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a}function F(a){F="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&"function"===typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?"symbol":typeof b};return F(a)}function I(a){for(var b=1;b<arguments.length;b++){var c=null!=arguments[b]?arguments[b]:{},h=Object.keys(c);"function"===typeof Object.getOwnPropertySymbols&&
(h=h.concat(Object.getOwnPropertySymbols(c).filter(function(b){return Object.getOwnPropertyDescriptor(c,b).enumerable})));h.forEach(function(b){v(a,b,c[b])})}return a}function R(a,b){for(var c=0;c<b.length;c++){var h=b[c];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function fa(a,b,c){b&&R(a.prototype,b);c&&R(a,c);return a}function J(a){J=Object.setPrototypeOf?Object.getPrototypeOf:function(b){return b.__proto__||Object.getPrototypeOf(b)};
return J(a)}function t(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return a}function ha(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});b&&K(a,b)}function K(a,b){K=Object.setPrototypeOf||function(c,b){c.__proto__=b;return c};return K(a,b)}function v(a,b,c){b in a?Object.defineProperty(a,
b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a}function L(a){L="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&"function"===typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?"symbol":typeof b};return L(a)}function ia(a){for(var b=1;b<arguments.length;b++){var c=null!=arguments[b]?arguments[b]:{},h=Object.keys(c);"function"===typeof Object.getOwnPropertySymbols&&(h=h.concat(Object.getOwnPropertySymbols(c).filter(function(b){return Object.getOwnPropertyDescriptor(c,
b).enumerable})));h.forEach(function(b){z(a,b,c[b])})}return a}function S(a,b){for(var c=0;c<b.length;c++){var h=b[c];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function ja(a,b,c){b&&S(a.prototype,b);c&&S(a,c);return a}function M(a){M=Object.setPrototypeOf?Object.getPrototypeOf:function(b){return b.__proto__||Object.getPrototypeOf(b)};return M(a)}function x(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
return a}function ka(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});b&&N(a,b)}function N(a,b){N=Object.setPrototypeOf||function(c,b){c.__proto__=b;return c};return N(a,b)}function z(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a}function T(a,b){for(var c=0;c<b.length;c++){var h=
b[c];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function la(a,b,c){b&&T(a.prototype,b);c&&T(a,c);return a}function U(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a}function V(a,b){for(var c=0;c<b.length;c++){var h=b[c];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function ma(a,b,c){b&&V(a.prototype,b);c&&
V(a,c);return a}function na(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a}function oa(a){if(Array.isArray(a)){var b=0;for(var c=Array(a.length);b<a.length;b++)c[b]=a[b];b=c}else b=void 0;b||(b=Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a)?Array.from(a):void 0);if(!(a=b))throw new TypeError("Invalid attempt to spread non-iterable instance");return a}function W(a,b){for(var c=0;c<b.length;c++){var h=
b[c];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function pa(a,b,c){b&&W(a.prototype,b);c&&W(a,c);return a}function X(a,b){for(var c=0;c<b.length;c++){var h=b[c];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function qa(a,b,c){b&&X(a.prototype,b);c&&X(a,c);return a}function Y(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):
a[b]=c;return a}function G(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a}function Z(a){for(var b=1;b<arguments.length;b++){var c=null!=arguments[b]?arguments[b]:{},h=Object.keys(c);"function"===typeof Object.getOwnPropertySymbols&&(h=h.concat(Object.getOwnPropertySymbols(c).filter(function(b){return Object.getOwnPropertyDescriptor(c,b).enumerable})));h.forEach(function(b){O(a,b,c[b])})}return a}function O(a,b,c){b in a?Object.defineProperty(a,
b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a}function aa(a,b){for(var c=0;c<b.length;c++){var h=b[c];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function ra(a,b,c){b&&aa(a.prototype,b);c&&aa(a,c);return a}g.r(d);a=g(0);var u=g.n(a),ba=function(a,b){var c=0;return function(){var h=(new Date).getTime();if(!(h-c<a))return c=h,b.apply(void 0,arguments)}},ca=function(a){return a.dataSet.reduce(function(a,c){c=
Math.max.apply(Math,n(c));return c>a?c:a},0)},sa=function(a){var b=a.data,c=a.scale,h=c*a.layerWidth/(b[b.length-1]-b[0]);return b.reduce(function(a,c,d){c=b[d+1]?a[d]+h*(b[d+1]-c):a[d]+h*(c-b[d-1]);return[].concat(n(a),[Math.floor(100*c)/100])},[-a.offset*c])},ta=function(a){var b=a.xCoords,c=a.layerHeight,h=a.maxValue;return a.data.reduce(function(a,d,e){return[].concat(n(a),[{x:b[e],y:Math.floor(6+(c-c/h*d))}])},[])},ua=function(a){return a.map(function(a){var c=a.columns.reduce(function(a,c){return k({},
a,l({},c[0],c.slice(1)))},{}),b=c.x;c=e(c,["x"]);return k({},a,{x:b,columns:c})})},P=function(a){if(isNaN(a))return a;for(var b=0;1E3<=a;)a/=1E3,b++;return"".concat(a.toPrecision(3)," ").concat(["","K","M","B","T"][b])},Q=function(a){return 1- --a*a*a*a};a=function(){function a(){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");r(this,"layers",{});r(this,"contexts",{});r(this,"touchDevice",!1);r(this,"parent",null);r(this,"parentSize",{});r(this,"dpr",2<(window.devicePixelRatio||
1)?2:window.devicePixelRatio);r(this,"prevState",null);r(this,"tickCount",30);r(this,"iteration",0);r(this,"isInitial",!0);r(this,"animations",{CHART_ANIMATION:[],XAXIS_ANIMATION:[],YAXIS_ANIMATION:[],CHART_SCENE_ANIMATION:[],WINDOW_ANIMATION:[],WINDOW_SCENE_ANIMATION:[]});this.touchDevice="ontouchstart"in document.documentElement}ea(a,[{key:"addAnimationID",value:function(a){this.animations[a.animationID].push(a.id)}},{key:"cancelPrevAnimations",value:function(a){a=a.animationID;var c=this.animations[a].pop();
this.animations[a].map(function(a){return window.cancelAnimationFrame(a)});this.animations[a]=[c]}},{key:"cancelAllAnimations",value:function(){var a={},c;for(c in this.animations)this.animations[c].map(function(a){return window.cancelAnimationFrame(a)}),a[c]=[];this.animations=a}},{key:"createLayer",value:function(a){a=a.layerID;var c=document.createElement("canvas");c.width=this.parentSize.width*this.dpr;c.height=this.parentSize.height*this.dpr;c.style.width="".concat(this.parentSize.width,"px");
c.style.height="".concat(this.parentSize.height,"px");var b=c.getContext("2d");b.scale(this.dpr,this.dpr);b.imageSmoothingEnabled=!1;this.layers=w({},this.layers,r({},a,c));this.contexts=w({},this.contexts,r({},a,b));return c}},{key:"getLayerContext",value:function(a){return this.contexts[a.layerID]}},{key:"getLayer",value:function(a){return this.layers[a.layerID]}},{key:"setLayerSettings",value:function(a){var c=a.settings;if((a=this.getLayerContext({layerID:a.layerID}))&&c)for(var b in c)a[b]=c[b]}},
{key:"withHandler",value:function(a){var c=a.handlerType,b=a.handler,d=a.options;d=void 0===d?{}:d;(a=this.getLayer({layerID:a.layerID}))&&a.addEventListener(c,b,d)}},{key:"clearContext",value:function(a){var c=this.width,b=this.height;this.getLayerContext({layerID:a.layerID}).clearRect(0,0,c,b)}},{key:"clearScene",value:function(){var a=this.contexts,c;for(c in a)this.clearContext({layerID:c})}},{key:"drawChart",value:function(a){var c=a.layerID,b=a.points,d=a.colors;a=a.isInitial;a=void 0===a?!1:
a;var e=this.getLayerContext({layerID:c}),g=this.chartHeight,f=this.prevState.points||{},m=Q(this.iteration/this.tickCount);this.clearContext({layerID:c});for(var k in b){e.beginPath();e.strokeStyle=d[k];for(var p=0;p<b[k].length-1;p++){var l=p,q=p+1,n=b[k][l],r=b[k][q];a||!f[k]?(e.moveTo(n.x,g-(g*m-n.y*m)),e.lineTo(r.x,g-(g*m-r.y*m))):f[k][l]&&f[k][q]&&(l=f[k][l],q=f[k][q],e.moveTo(l.x+(n.x-l.x)*m,l.y+(n.y-l.y)*m),e.lineTo(q.x+(r.x-q.x)*m,q.y+(r.y-q.y)*m))}e.lineWidth=2;e.stroke();e.closePath()}this.iteration+=
1;this.iteration<=this.tickCount&&(c=window.requestAnimationFrame(this.drawChart.bind(this,{layerID:c,points:b,colors:d,isInitial:a})),this.addAnimationID({animationID:"CHART_ANIMATION",id:c}))}},{key:"getActiveColumns",value:function(a){var c=a.activeCharts;a=a.columns;var b={},d;for(d in c)c[d]&&(b[d]=a[d]);return b}},{key:"recalculate",value:function(a){a=a.showFullRange;a=void 0===a?!0:a;var c=this._visibleBounds,b=c.fromIndex,d=c.toIndex;c=c.windowPosition;var e=this._rawData,g=e.columns;e=e.x;
var f=this.chartHeight,m=c?c.width:120,p=c?c.x:0;c=this.getActiveColumns({activeCharts:this._activeCharts,columns:g});var n=w({},c);if(d&&!a)for(var C in c)n[C]=g[C].slice(b,d);C=ca({dataSet:Object.values(n)});b=ca({dataSet:Object.values(c)});d=[];if(!a){d=f-11;f=d/8;for(g=[];0<=d;)g.push(Math.floor(100*d)/100),d-=f;d=g}a=sa({layerWidth:this.width,data:e,scale:a?1:this.width/m,offset:a?0:p});e=this.chartHeight;m={};for(q in c)m=k({},m,l({},q,ta({xCoords:a,layerHeight:e,maxValue:C,data:c[q]})));var q=
m;this.prevState=this.prevState?w({},this.prevState,{maxInColumns:this.maxInColumns,localMaxInColumns:this.localMaxInColumns,xCoords:this.xCoords,points:this.points,yCoords:this.yCoords}):{maxInColumns:b,localMaxInColumns:C,xCoords:a,points:q,yCoords:d};this.maxInColumns=b;this.localMaxInColumns=C;this.xCoords=a;this.points=q;this.yCoords=d}},{key:"getCursorPosition",value:function(a){var c=this.parentSize;return this.touchDevice&&a.touches&&a.touches.length?{x:a.touches[0].clientX-c.x,y:a.touches[0].clientY}:
{x:a.clientX-c.x,y:a.clientY}}},{key:"setParentSize",value:function(){return this.parentSize=this.parent.getBoundingClientRect()}},{key:"width",get:function(){return this.parentSize.width}},{key:"height",get:function(){return this.parentSize.height}}]);return a}();d=g(2);var H=g.n(d),A,va=(A={},E(A,"SET_VISIBLE_BOUNDS",function(a,b){a.commit("SET_VISIBLE_BOUNDS",{payload:b.payload,meta:b.meta})}),E(A,"TOGGLE_ACTIVE_CHART",function(a,b){a.commit("TOGGLE_ACTIVE_CHART",{payload:b.payload,meta:b.meta})}),
E(A,"TOGGLE_NIGHT_MODE",function(a,b){a.commit("TOGGLE_NIGHT_MODE",{payload:b.payload,meta:b.meta})}),E(A,"TOGGLE_MOOVING_STATE",function(a,b){a.commit("TOGGLE_MOOVING_STATE",{payload:b.payload,meta:b.meta})}),A),wa=function(a){function b(a){var c=a.parent,d=a.data,e=a.store,g=a.chartID;if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");a=J(b).call(this);a=!a||"object"!==F(a)&&"function"!==typeof a?t(this):a;v(t(a),"borderThreshold",10);v(t(a),"windowPosition",{});v(t(a),
"mousePosition",{x:0,y:0});v(t(a),"prevMosuePosition",{x:0,y:0});v(t(a),"mouseDown",!1);v(t(a),"mouseIn",!1);v(t(a),"animationID",null);v(t(a),"transform",null);v(t(a),"hoverType",null);v(t(a),"isMooving",!1);v(t(a),"_delta",0);v(t(a),"moveTimer",void 0);var f=t(a);f.parent=c;f._rawData=d;f.store=e;f.setParentSize();f.chartHeight=f.parentSize.height;f.chartID=g;f.borderThreshold*=f.dpr;f._visibleBounds=f.store.state.charts[f.chartID].ui.visibleBounds;f._activeCharts=f.store.state.charts[f.chartID].ui.activeCharts;
f.nightMode=f.store.state.nightMode;c=f.createLayer({layerID:"WINDOW_LAYER"});d=f.createLayer({layerID:"BASE_LAYER"});c.classList.add(H.a.preview,H.a.previewWindow);d.classList.add(H.a.preview,H.a.previewBase);f.recalculate({showFullRange:!0});f.setLayerSettings({layerID:"WINDOW_LAYER",settings:{globalCompositeOperation:"destination-over"}});f.windowPosition={x:5,y:0,width:120,height:f.height};f.sliceVisiblePart();c=window.requestAnimationFrame(f.drawScene.bind(f));f.addAnimationID({animationID:"WINDOW_SCENE_ANIMATION",
id:c});f.touchDevice?(f.withHandler({layerID:"WINDOW_LAYER",handlerType:"touchmove",handler:f.onMouseMove.bind(f),options:{passive:!0}}),f.withHandler({layerID:"WINDOW_LAYER",handlerType:"touchstart",handler:f.onTouchStart.bind(f),options:{passive:!0}}),f.withHandler({layerID:"WINDOW_LAYER",handlerType:"touchend",handler:f.onTouchEnd.bind(f)}),f.withHandler({layerID:"WINDOW_LAYER",handlerType:"touchcancel",handler:f.onTouchEnd.bind(f)})):(f.withHandler({layerID:"WINDOW_LAYER",handlerType:"mousemove",
handler:f.onMouseMove.bind(f)}),f.withHandler({layerID:"WINDOW_LAYER",handlerType:"mouseout",handler:f.onMouseOut.bind(f)}),f.withHandler({layerID:"WINDOW_LAYER",handlerType:"mouseenter",handler:f.onMouseEnter.bind(f)}),f.withHandler({layerID:"WINDOW_LAYER",handlerType:"mousedown",handler:f.onMouseDown.bind(f)}),f.withHandler({layerID:"WINDOW_LAYER",handlerType:"mouseup",handler:f.onMouseUp.bind(f)}));e.events.subscribe({eventName:"stateChange",callback:f.storeCallback.bind(f)});return a}ha(b,a);
fa(b,[{key:"storeCallback",value:function(a){a=a.meta;if(a.id===this.chartID||"ALL"===a.id){this.isInitial=!1;this.iteration=0;this._visibleBounds=this.store.state.charts[this.chartID].ui.visibleBounds;this._activeCharts=this.store.state.charts[this.chartID].ui.activeCharts;this.nightMode=this.store.state.nightMode;this.recalculate({showFullRange:!0});a=this.store.state.charts[this.chartID].ui.isMooving;this.cancelAllAnimations();var c=window.requestAnimationFrame(this.drawScene.bind(this));this.addAnimationID({animationID:"WINDOW_SCENE_ANIMATION",
id:c});this.isMooving=a}}},{key:"drawScene",value:function(){this.drawWindow();this.drawChart({layerID:"BASE_LAYER",points:this.points,colors:this._rawData.colors,isInitial:this.isInitial})}},{key:"setHoverType",value:function(a){a=this.getCursorPosition(a.event);var c=this.windowPosition,b=this.borderThreshold;return this.hoverType=c.x+c.width-b<=a.x&&a.x<=c.x+c.width+b?"HOVER_RIGHT_BORDER":a.x-b<=c.x&&c.x<=a.x+b?"HOVER_LEFT_BORDER":a.x>c.x&&a.x<c.x+c.width?"HOVER_INNER":null}},{key:"onMouseMove",
value:function(a){var c=this.getCursorPosition(a),b=this.mouseDown,d=this.mousePosition,e=this.getLayer({layerID:"WINDOW_LAYER"}),f=this.hoverType;f&&b||(f=this.setHoverType({event:a}));switch(f){case "HOVER_LEFT_BORDER":e.style.cursor="w-resize";this.transform="left";break;case "HOVER_RIGHT_BORDER":e.style.cursor="e-resize";this.transform="right";break;case "HOVER_INNER":this.transform=e.style.cursor="move";break;default:e.style.cursor="default",this.transform=null}b&&(this.prevMosuePosition=d,this.mousePosition=
c,this.sliceVisiblePart())}},{key:"onMouseDown",value:function(a){a.preventDefault();a=this.getCursorPosition(a);this.mouseDown=!0;this.mousePosition=this.prevMosuePosition=a;this.toggleMoovingState({isMooving:!0})}},{key:"onTouchStart",value:function(a){a.preventDefault();this.mouseIn=!0;this.setHoverType({event:a});this.onMouseDown(a)}},{key:"onTouchEnd",value:function(a){this.mouseIn=!1;this.onMouseUp(a)}},{key:"onMouseUp",value:function(){this.mouseDown=!1;this.toggleMoovingState({isMooving:!1})}},
{key:"onMouseEnter",value:function(){this.mouseIn=!0}},{key:"onMouseOut",value:function(){this.mouseDown=this.mouseIn=!1;this.toggleMoovingState({isMooving:!1})}},{key:"drawWindow",value:function(){var a=this.windowPosition,b=this.transform,d=this.delta,e=this.mouseDelta,g=this.nightMode,f=this.getLayerContext({layerID:"WINDOW_LAYER"}),m=a;this.clearContext({layerID:"WINDOW_LAYER"});"move"===b?m=I({},m,{x:d}):"left"===b?(b=a.width-e,m=I({},m,{x:a.x+e,width:50>b?50:b})):"right"===b&&(b=a.width+e,m=
I({},m,{width:50>b?50:b}));this.windowPosition=m;f.strokeStyle=g?"rgba(65, 86, 106, 0.9)":"rgba(221, 234, 243, 0.9)";f.lineWidth=10;f.strokeRect(m.x,m.y,m.width,m.height);f.save();this.drawOverlay()}},{key:"drawOverlay",value:function(){var a=this.width,b=this.height,d=this.windowPosition,e=this.nightMode,g=this.getLayerContext({layerID:"WINDOW_LAYER"});g.fillStyle=e?"rgba(31, 42, 55, 0.6)":"rgba(245, 249, 251, 0.8)";g.fillRect(d.width+d.x,0,a-d.width,b);g.fillRect(0,0,d.x,b)}},{key:"sliceVisiblePart",
value:function(){var a=this.windowPosition,b=this.xCoords,d=this.chartID;this.store.dispatch({actionKey:"SET_VISIBLE_BOUNDS",meta:{id:d},payload:{chartID:d,visibleBounds:{fromIndex:b.findIndex(function(b){return b>=a.x}),toIndex:b.findIndex(function(b){return b>=a.x+a.width}),windowPosition:a}}})}},{key:"toggleMoovingState",value:function(a){a=a.isMooving;var b=this.store,c=this.chartID;a!==this.isMooving&&b.dispatch({actionKey:"TOGGLE_MOOVING_STATE",meta:{id:c},payload:{chartID:c,isMooving:a}})}},
{key:"delta",get:function(){var a=this.windowPosition,b=this.width,d=this._delta+this.mouseDelta;10>d?d=0:d>b-a.width-10&&(d=a.x);return this._delta=d}},{key:"mouseDelta",get:function(){return this.mousePosition.x-this.prevMosuePosition.x}}]);return b}(a),xa=function(a){function b(a){var c=a.parent,d=a.data,e=a.store,g=a.chartID;if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");a=M(b).call(this);a=!a||"object"!==L(a)&&"function"!==typeof a?x(this):a;z(x(a),"_rawData",
{});z(x(a),"_visibleBounds",{fromIndex:0,toIndex:0});z(x(a),"_activeIndex",-1);z(x(a),"_mousePosition",{});z(x(a),"_hoverThreshold",10);z(x(a),"_opacity",0);z(x(a),"isMooving",!1);z(x(a),"xAxisIteration",0);z(x(a),"yAxisIteration",0);var f=x(a);f.parent=c;f._rawData=d;f.store=e;f.chartID=g;f.setParentSize();f.chartHeight=f.parentSize.height-15;c=f.createLayer({layerID:"LINE_CHART_LAYER"});d=f.createLayer({layerID:"X_AXIS_LAYER"});g=f.createLayer({layerID:"LINES_LAYER"});var m=f.createLayer({layerID:"HOVERABLE_LAYER"}),
k=f.createLayer({layerID:"TOOLTIP_LAYER"});c.classList.add(u.a.layer);d.classList.add(u.a.layer);g.classList.add(u.a.layer);m.classList.add(u.a.layer);k.classList.add(u.a.layer);f._visibleBounds=e.state.charts[f.chartID].ui.visibleBounds;f._activeCharts=e.state.charts[f.chartID].ui.activeCharts;f.isInitial=!0;f.setAverageLabelWidth();f.recalculate({showFullRange:!1});c=window.requestAnimationFrame(f.drawScene.bind(f));f.addAnimationID({animationID:"CHART_SCENE_ANIMATION",id:c});f.touchDevice?(f.withHandler({layerID:"TOOLTIP_LAYER",
handlerType:"touchstart",handler:f.onMouseMove.bind(f),options:{passive:!0}}),f.withHandler({layerID:"TOOLTIP_LAYER",handlerType:"touchmove",handler:f.throttledMosueMove.bind(f),options:{passive:!0}}),f.withHandler({layerID:"TOOLTIP_LAYER",handlerType:"touchend",handler:f.hideTooltip.bind(f)})):(f.withHandler({layerID:"TOOLTIP_LAYER",handlerType:"mousemove",handler:f.throttledMosueMove.bind(f)}),f.withHandler({layerID:"TOOLTIP_LAYER",handlerType:"mouseout",handler:f.hideTooltip.bind(f)}));e.events.subscribe({eventName:"stateChange",
callback:f.storeCallback.bind(f)});return a}ka(b,a);ja(b,[{key:"storeCallback",value:function(a){a=a.meta;if(a.id===this.chartID||"ALL"===a.id){this.isInitial=!1;this._visibleBounds=this.store.state.charts[this.chartID].ui.visibleBounds;this._activeCharts=this.store.state.charts[this.chartID].ui.activeCharts;this.nightMode=this.store.state.nightMode;a=this.store.state.charts[this.chartID].ui.isMooving;this.recalculate({showFullRange:!1});this.yAxisAnimationID=this.xAxisIteration=this.iteration=0;
this.cancelAllAnimations();var b=window.requestAnimationFrame(this.drawScene.bind(this));this.addAnimationID({animationID:"CHART_SCENE_ANIMATION",id:b});this.isMooving=a}}},{key:"hideTooltip",value:function(){this.clearContext({layerID:"HOVERABLE_LAYER"});this.clearContext({layerID:"TOOLTIP_LAYER"})}},{key:"dateLabel",value:function(a){var b=a.additionalOtions;return(new Date(a.UNIXDate)).toLocaleDateString("en-US",ia({month:"short",day:"numeric"},void 0===b?{}:b))}},{key:"drawScene",value:function(){this.clearScene();
this.drawChart({layerID:"LINE_CHART_LAYER",points:this.points,colors:this._rawData.colors,isInitial:this.isInitial});this.drawXAxis();this.drawLines()}},{key:"drawXAxis",value:function(){var a=this.chartHeight,b=this.width,d=this.nightMode,e=this.getLayerContext({layerID:"X_AXIS_LAYER"});this.clearContext({layerID:"X_AXIS_LAYER"});e.strokeStyle=d?"rgb(49, 61, 76)":"rgb(236, 240, 243)";e.beginPath();e.moveTo(0,a-11);e.lineTo(b,a-11);e.stroke();e.fill();e.closePath();e.beginPath();this.drawXAxisTicks();
e.closePath()}},{key:"setAverageLabelWidth",value:function(){var a=this.getLayerContext({layerID:"X_AXIS_LAYER"}),b=this._rawData,d=this.dateLabel,e=b.x.reduce(function(c,h,e){h=d({UNIXDate:b.x[e]});h=a.measureText(h);return c+h.width},0)/b.x.length;this._averageLabelWdth=Math.round(e)}},{key:"drawXAxisTicks",value:function(){var a=this.chartHeight,b=this.width,d=this.xCoords,e=this._rawData,g=this.dateLabel,f=this._averageLabelWdth,m=this.visibleBounds,k=this.nightMode,p=this.prevState,l=this.getLayerContext({layerID:"X_AXIS_LAYER"}),
q=m.fromIndex,n=m.toIndex;p=p?p.xCoords:null;m=Q(this.xAxisIteration/this.tickCount);this.clearContext({layerID:"X_AXIS_LAYER"});l.font="lighter ".concat(11,"px Helvetica");l.fillStyle=k?"rgb(85 ,103, 119)":"rgb(150, 162, 170)";b=Math.round(b/(f+40));q=d.slice(q,n);q=Math.round(q.length/b);for(b=0;b<=d.length;b+=q)f=g({UNIXDate:e.x[b]}),l.fillText(f,p[b]+(d[b]-p[b])*m,a);this.xAxisIteration+=1;this.xAxisIteration<=this.tickCount?(a=window.requestAnimationFrame(this.drawXAxisTicks.bind(this)),this.addAnimationID({animationID:"XAXIS_ANIMATION",
id:a}),this.cancelPrevAnimations({animationID:"XAXIS_ANIMATION"})):this.xAxisIteration=0}},{key:"drawLines",value:function(){var a=this.width,b=this.nightMode,d=this.maxInColumns,e=this.localMaxInColumns,g=this.yCoords,f=this.prevState.yCoords,m=this.getLayerContext({layerID:"LINES_LAYER"}),k=Q(this.yAxisIteration/this.tickCount);e/=8;this.clearContext({layerID:"LINES_LAYER"});m.strokeStyle=b?"rgb(41, 53, 67)":"rgb(242, 244, 245)";m.fillStyle=b?"rgb(85 ,103, 119)":"rgb(150, 162, 170)";m.font="lighter ".concat(9,
"px Helvetica");m.beginPath();b=0;for(var p=d,l=0;l<=g.length;l++){var n=f[l]+(g[l]-f[l])*k;m.moveTo(0,n);m.lineTo(a,n);m.fillText(b?P(b):0,0,n-7);p-=e;b=d-p}m.stroke();m.closePath();this.yAxisIteration+=1;this.yAxisIteration<=this.tickCount?(a=window.requestAnimationFrame(this.drawLines.bind(this)),this.addAnimationID({animationID:"YAXIS_ANIMATION",id:a}),this.cancelPrevAnimations({animationID:"XAXIS_ANIMATION"})):this.yAxisIteration=0}},{key:"onMouseMove",value:function(a){var b=this.getCursorPosition(a);
a=this.xCoords;var c=this._hoverThreshold;this._mousePosition=b;this._activeIndex=a.findIndex(function(a){return b.x>=a-c&&b.x<=a+c?!0:!1});window.requestAnimationFrame(this.drawOnHover.bind(this))}},{key:"drawOnHover",value:function(){var a=this._activeIndex,b=this.xCoords,d=this.chartHeight,e=this._rawData,g=this.points,f=this.nightMode,m=this.getLayerContext({layerID:"HOVERABLE_LAYER"});e=e.colors;this.clearContext({layerID:"HOVERABLE_LAYER"});if(-1<a){b=b[a];m.fillStyle=f?"rgb(36, 47, 61)":"rgb(255, 255, 255)";
m.strokeStyle=f?"rgb(60, 74, 89)":"rgb(223, 230, 235)";m.beginPath();m.lineWidth=1;m.moveTo(b,0);m.lineTo(b,d-11);m.stroke();m.closePath();for(var k in g)d=g[k][a].y,m.strokeStyle=e[k],m.lineWidth=4,m.beginPath(),m.arc(b,d,4,0,2*Math.PI),m.stroke(),m.fill(),m.closePath()}this.drawTooltip()}},{key:"calculateTooltipWidth",value:function(){var a=this.getLayerContext({layerID:"TOOLTIP_LAYER"}),b=this._activeIndex,d=this._activeCharts,e=this._rawData.columns,g=0,f=0,m;for(m in e)if(d[m]){var k=P(e[m][b]);
g+=a.measureText(k).width;f++}a=Math.round(g)+5*(f+1);return 100>a?100:a}},{key:"drawRoundRect",value:function(a){var b=a.context,c=a.x,d=a.y,e=a.width;a=a.height;var f=this.nightMode;b.beginPath();b.lineWidth=1;b.moveTo(c+6,d);b.lineTo(c+e-6,d);b.quadraticCurveTo(c+e,d,c+e,d+6);b.lineTo(c+e,d+a-6);b.quadraticCurveTo(c+e,d+a,c+e-6,d+a);b.lineTo(c+6,d+a);b.quadraticCurveTo(c,d+a,c,d+a-6);b.lineTo(c,d+6);b.quadraticCurveTo(c,d,c+6,d);b.fillStyle=f?"rgb(37, 50, 64)":"rgb(255, 255, 255)";b.strokeStyle=
f?"rgb(32, 42, 54)":"rgb(227, 227, 227)";b.fill();b.stroke();b.closePath()}},{key:"drawTooltipText",value:function(a){var b=a.context,c=a.date,d=a.x;a=a.y;var e=this._activeIndex,f=this._rawData,g=this.nightMode,k=this._activeCharts;b.font="lighter 15px Helvetica";b.fillStyle=g?"rgb(255, 255, 255)":"rgb(34, 34, 34)";b.fillText(c,d+5,a+25);b.save();c=5;for(var l in f.columns)if(k[l]){b.fillStyle=f.colors[l];g=P(f.columns[l][e]);var p=f.names[l];b.fillText(g,d+c,a+50);b.fillText(p,d+c,a+70);c=c+b.measureText(g).width+
5;b.save()}}},{key:"drawTooltip",value:function(){var a=this.getLayerContext({layerID:"TOOLTIP_LAYER"}),b=this._activeIndex,d=this._rawData,e=this.dateLabel,g=this.width,f=this.xCoords[b]+20;this.clearContext({layerID:"TOOLTIP_LAYER"});if(-1<b){var k=this.calculateTooltipWidth();b=e({UNIXDate:d.x[b],additionalOtions:{weekday:"short"}});f+k>g&&(f-=k+40);this.drawRoundRect({context:a,x:f,y:20,width:k,height:80});this.drawTooltipText({context:a,date:b,x:f,y:20})}}},{key:"visibleBounds",get:function(){return this._visibleBounds}},
{key:"rawData",get:function(){return this._rawData}},{key:"throttledMosueMove",get:function(){return ba(10,this.onMouseMove.bind(this))}}]);return b}(a);A=g(1);var B=g.n(A),ya=function(){function a(b){var c=b.store,d=b.id;b=b.chartID;if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");U(this,"_active",!0);U(this,"_id",void 0);this._id=d;this.store=c;this.chartID=b;this.buttonWrapper=document.createElement("div");this.buttonWrapper.classList.add(B.a.buttonWrapper);this.buttonWrapper.classList.add(u.a.buttonWrapper);
this.buttonWrapper.classList.add(B.a.active);c=document.createElement("div");b=document.createElementNS("http://www.w3.org/2000/svg","svg");var e=document.createElementNS("http://www.w3.org/2000/svg","circle"),g=document.createElementNS("http://www.w3.org/2000/svg","path");b.classList.add(B.a.buttonLabel);e.classList.add(B.a.buttonLabelCircle);g.classList.add(B.a.buttonLabelIcon);b.setAttribute("viewBox","0 0 52 52");e.setAttribute("cx",26);e.setAttribute("cy",26);e.setAttribute("r",24);e.setAttribute("stroke",
this.store.state.charts[this.chartID].orm.data.colors[d]);e.setAttribute("fill",this.store.state.charts[this.chartID].orm.data.colors[d]);g.setAttribute("d","M14.1 27.2l7.1 7.2 16.7-16.8");b.appendChild(e);b.appendChild(g);c.classList.add(B.a.buttonText);c.innerText=this.store.state.charts[this.chartID].orm.data.names[d];this.buttonWrapper.appendChild(b);this.buttonWrapper.appendChild(c);this.buttonWrapper.addEventListener("click",this.throttledClickHandler.bind(this))}la(a,[{key:"clickHandler",value:function(a){a.preventDefault();
this.buttonWrapper.classList.toggle(B.a.active);this._active=!this._active;this.store.dispatch({actionKey:"TOGGLE_ACTIVE_CHART",meta:{id:this.chartID},payload:{chartID:this.chartID,id:this._id,state:this._active}})}},{key:"throttledClickHandler",get:function(){return ba(500,this.clickHandler.bind(this))}}]);return a}();A=g(3);var da=g.n(A),za=function(){function a(b){var c=b.store,d=b.wrapper;if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");na(this,"nightMode",!1);
var e=this,g=document.createElement("div");e.modeLinkWrapper=document.createElement("div");e.modeLinkWrapper.classList.add(da.a.modeLinkWrapper);e.modeLinkWrapper.classList.add(u.a.modeLinkWrapper);g.classList.add(da.a.modeLink);g.classList.add(u.a.modeLink);g.innerHTML=e.modeText;e.modeLinkWrapper.appendChild(g);e.modeLinkWrapper.addEventListener("click",function(){d.classList.toggle(u.a.nightMode);e.nightMode=!e.nightMode;g.innerHTML=e.modeText;c.dispatch({actionKey:"TOGGLE_NIGHT_MODE",meta:{id:"ALL"},
payload:{nightMode:e.nightMode}})})}ma(a,[{key:"mode",get:function(){return this.nightMode?"Day":"Night"}},{key:"modeText",get:function(){return"Switch to ".concat(this.mode," Mode")}}]);return a}(),Aa=function(){function a(){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");this.events=new Map}pa(a,[{key:"subscribe",value:function(a){var b=a.eventName;a=a.callback;var d=this.events;d.has(b)||d.set(b,[]);d.set(b,[].concat(oa(d.get(b)),[a]))}},{key:"publish",value:function(a){var b=
a.eventName,d=a.data,e=void 0===d?{}:d;a=a.meta;var g=void 0===a?{}:a;a=this.events;return a.has(b)?a.get(b).map(function(a){return a({data:e,meta:g})}):[]}}]);return a}(),Ba=function(){function a(b){var c=b.actions;c=void 0===c?{}:c;var d=b.mutations;d=void 0===d?{}:d;b=b.state;b=void 0===b?{}:b;if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");Y(this,"actions",{});Y(this,"mutations",{});this.events=new Aa;this.actions=c;this.mutations=d;this.state=b}qa(a,[{key:"dispatch",
value:function(a){var b=this.actions[a.actionKey];return b?b(this,{payload:a.payload,meta:a.meta}):!1}},{key:"commit",value:function(a,c){var b=c.meta;a=this.mutations[a];if(!a)return!1;c=Object.assign(this.state,a(this.state,{payload:c.payload,meta:b}));this.events.publish({eventName:"stateChange",data:c,meta:b});return c}}]);return a}(),D,Ca=(D={},G(D,"SET_VISIBLE_BOUNDS",function(a,b){b=b.payload;a.charts[b.chartID].ui.visibleBounds=b.visibleBounds;return a}),G(D,"TOGGLE_ACTIVE_CHART",function(a,
b){b=b.payload;a.charts[b.chartID].ui.activeCharts[b.id]=b.state;return a}),G(D,"TOGGLE_NIGHT_MODE",function(a,b){a.nightMode=b.payload.nightMode;return a}),G(D,"TOGGLE_MOOVING_STATE",function(a,b){b=b.payload;a.charts[b.chartID].ui.isMooving=b.isMooving;return a}),D);new (function(){function a(b){b=b.data;if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");var c=this;c.data=ua(b);c.store=c.initializeStore({data:c.data,rawData:b});c.appContainter=document.getElementById("app");
c.wrapperContainer=document.getElementById("wrapper");c.data.map(c.throttledInit.bind(c));var d=new za({store:c.store,wrapper:c.wrapperContainer});setTimeout(function(){return c.appContainter.appendChild(d.modeLinkWrapper)},1500*c.data.length)}ra(a,[{key:"throttledInit",value:function(a,c){return setTimeout(this.initializeChart.bind(this,{chartData:a,store:this.store,index:c,chartID:"CHART_ID_".concat(c)}),1500*c)}},{key:"initializeStore",value:function(a){var b=a.data,d=a.rawData;a=b.reduce(function(a,
c,e){c=Object.keys(c.columns).reduce(function(a,b){return Z({},a,O({},b,!0))},{});return Z({},a,O({},"CHART_ID_".concat(e),{ui:{visibleBounds:{},activeCharts:c},orm:{_rawData:d[e],data:b[e]}}))},{});return new Ba({actions:va,mutations:Ca,state:{nightMode:!1,charts:a}})}},{key:"initializeChart",value:function(a){var b=a.chartData,d=a.store,e=a.index,g=a.chartID,k=this.appContainter;a=document.createElement("div");var f=document.createElement("h2"),m=document.createElement("div"),l=document.createElement("div"),
n=document.createElement("div");f.classList.add(u.a.chartTitle);f.innerHTML="Graph # ".concat(e+1);k.appendChild(a);a.appendChild(f);a.appendChild(l);a.appendChild(m);a.classList.add(u.a.chartContainer);m.classList.add(u.a.previewWrapper);l.classList.add(u.a.chartWrapper);n.classList.add(u.a.buttonsWrapper);e=new wa({parent:m,store:d,data:b,chartID:g});k=new xa({parent:l,store:d,data:b,chartID:g});l.appendChild(k.getLayer({layerID:"X_AXIS_LAYER"}));l.appendChild(k.getLayer({layerID:"LINES_LAYER"}));
l.appendChild(k.getLayer({layerID:"LINE_CHART_LAYER"}));l.appendChild(k.getLayer({layerID:"HOVERABLE_LAYER"}));l.appendChild(k.getLayer({layerID:"TOOLTIP_LAYER"}));m.appendChild(e.getLayer({layerID:"BASE_LAYER"}));m.appendChild(e.getLayer({layerID:"WINDOW_LAYER"}));Object.keys(b.names).map(function(a){a=new ya({store:d,id:a,chartID:g});n.appendChild(a.buttonWrapper);return a});a.appendChild(n)}}]);return a}())({data:window.data})}]);}).call(this || window)
