(function(){'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,f){a!=Array.prototype&&a!=Object.prototype&&(a[c]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,c){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(f){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(f||"")+"_"+c++,f)}var c=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,c){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var f=0,d={next:function(){if(f<a.length){var k=f++;return{value:c(k,a[k]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,c,f,d){if(c){f=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var k=a[d];k in f||(f[k]={});f=f[k]}a=a[a.length-1];d=f[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,f,d){f=null!=f?f:function(a){return a};var c=[],l="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof l){a=l.call(a);for(var n=0;!(l=a.next()).done;)c.push(f.call(d,l.value,n++))}else for(l=a.length,n=0;n<l;n++)c.push(f.call(d,a[n],n));return c}},"es6","es3");$jscomp.owns=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};
$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var c=[],d;for(d in a)$jscomp.owns(a,d)&&c.push(a[d]);return c}},"es8","es3");$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},c={};try{return c.__proto__=a,c.a}catch(f){}return!1};$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.polyfill("Object.setPrototypeOf",function(a){return a||$jscomp.setPrototypeOf},"es6","es5");$jscomp.findInternal=function(a,c,f){a instanceof String&&(a=String(a));for(var d=a.length,k=0;k<d;k++){var l=a[k];if(c.call(f,l,k,a))return{i:k,v:l}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.findIndex",function(a){return a?a:function(a,f){return $jscomp.findInternal(this,a,f).i}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,f,d){var c=this.length||0;0>f&&(f=Math.max(0,c+f));if(null==d||d>c)d=c;d=Number(d);0>d&&(d=Math.max(0,c+d));for(f=Number(f||0);f<d;f++)this[f]=a;return this}},"es6","es3");$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},c=Object.create(new $jscomp.global.Proxy(a,{get:function(f,d,k){return f==a&&"q"==d&&k==c}}));return!0===c.q}catch(f){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;
$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill("WeakMap",function(a){function c(){if(!a||!Object.seal)return!1;try{var y=Object.seal({}),d=Object.seal({}),c=new a([[y,2],[d,3]]);if(2!=c.get(y)||3!=c.get(d))return!1;c.delete(y);c.set(d,4);return!c.has(y)&&4==c.get(d)}catch(E){return!1}}function f(){}function d(a){if(!$jscomp.owns(a,l)){var d=new f;$jscomp.defineProperty(a,l,{value:d})}}function k(a){var y=Object[a];y&&(Object[a]=function(a){if(a instanceof f)return a;d(a);return y(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&
$jscomp.ES6_CONFORMANCE)return a}else if(c())return a;var l="$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var n=0,w=function(a){this.id_=(n+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var d;!(d=a.next()).done;)d=d.value,this.set(d[0],d[1])}};w.prototype.set=function(a,c){d(a);if(!$jscomp.owns(a,l))throw Error("WeakMap key fail: "+a);a[l][this.id_]=c;return this};w.prototype.get=function(a){return $jscomp.owns(a,l)?a[l][this.id_]:void 0};w.prototype.has=
function(a){return $jscomp.owns(a,l)&&$jscomp.owns(a[l],this.id_)};w.prototype.delete=function(a){return $jscomp.owns(a,l)&&$jscomp.owns(a[l],this.id_)?delete a[l][this.id_]:!1};return w},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function c(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),c=new a($jscomp.makeIterator([[d,"s"]]));if("s"!=c.get(d)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var f=c.entries(),k=f.next();if(k.done||k.value[0]!=d||"s"!=k.value[1])return!1;k=f.next();return k.done||4!=k.value[0].x||"t"!=k.value[1]||!f.next().done?!1:!0}catch(F){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(c())return a;$jscomp.initSymbolIterator();var f=new WeakMap,d=function(a){this.data_={};this.head_=n();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var d;!(d=a.next()).done;)d=d.value,this.set(d[0],d[1])}};d.prototype.set=function(a,d){a=0===a?0:a;var c=k(this,a);c.list||(c.list=this.data_[c.id]=[]);c.entry?c.entry.value=d:(c.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:d},c.list.push(c.entry),this.head_.previous.next=c.entry,this.head_.previous=c.entry,this.size++);return this};d.prototype.delete=function(a){a=k(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=n();this.size=0};d.prototype.has=function(a){return!!k(this,a).entry};
d.prototype.get=function(a){return(a=k(this,a).entry)&&a.value};d.prototype.entries=function(){return l(this,function(a){return[a.key,a.value]})};d.prototype.keys=function(){return l(this,function(a){return a.key})};d.prototype.values=function(){return l(this,function(a){return a.value})};d.prototype.forEach=function(a,d){for(var c=this.entries(),f;!(f=c.next()).done;)f=f.value,a.call(d,f[1],f[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var k=function(a,d){var c=d&&typeof d;"object"==
c||"function"==c?f.has(d)?c=f.get(d):(c=""+ ++w,f.set(d,c)):c="p_"+d;var k=a.data_[c];if(k&&$jscomp.owns(a.data_,c))for(a=0;a<k.length;a++){var l=k[a];if(d!==d&&l.key!==l.key||d===l.key)return{id:c,list:k,index:a,entry:l}}return{id:c,list:k,index:-1,entry:void 0}},l=function(a,d){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:d(c)};c=null}return{done:!0,value:void 0}})},n=function(){var a={};return a.previous=
a.next=a.head=a},w=0;return d},"es6","es3");$jscomp.assign="function"==typeof Object.assign?Object.assign:function(a,c){for(var f=1;f<arguments.length;f++){var d=arguments[f];if(d)for(var k in d)$jscomp.owns(d,k)&&(a[k]=d[k])}return a};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");
(function(a){function c(d){if(f[d])return f[d].exports;var k=f[d]={i:d,l:!1,exports:{}};a[d].call(k.exports,k,k.exports,c);k.l=!0;return k.exports}var f={};c.m=a;c.c=f;c.d=function(a,f,l){c.o(a,f)||Object.defineProperty(a,f,{enumerable:!0,get:l})};c.r=function(a){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})};c.t=function(a,f){f&1&&(a=c(a));if(f&8||f&4&&"object"===typeof a&&a&&a.__esModule)return a;
var d=Object.create(null);c.r(d);Object.defineProperty(d,"default",{enumerable:!0,value:a});if(f&2&&"string"!=typeof a)for(var k in a)c.d(d,k,function(c){return a[c]}.bind(null,k));return d};c.n=function(a){var d=a&&a.__esModule?function(){return a["default"]}:function(){return a};c.d(d,"a",d);return d};c.o=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};c.p="";return c(c.s=4)})([function(a,c,f){a.exports={chartContainer:"_3Kp5o7RruKidI1ceIQDvrE",chartTitle:"_2a8wANmODgPnccDUldcOqD",
previewWrapper:"T_lXQnUaSe4e8dEJCGe_l",chartWrapper:"_3jqLxlEZqRswFEbI3Tilqk",layer:"_15bywRdIlzdk53NEYr9Gl3",buttonsWrapper:"cj9mCMN3rkeSucQueDpUW",nightMode:"mKtZwWmFkxBh9DH71crEU",modeLink:"_2cfANduKwNkCL4yvaEX7Bo",modeLinkWrapper:"_3-azWK_-3-MDhKEhNLVPOl",buttonWrapper:"_1asqrW83RplQ0RdACo-zLX"}},function(a,c,f){a.exports={active:"_3PbXgXpXDhNxxyXkhkmECK",buttonLabelCircle:"wueb78C8VRaqMEut8wDN4",buttonLabelIcon:"_3Ol41HhAZvwbofm0lIQ-0X",buttonWrapper:"_1Y0hOJE83-BbA0xw2Wq8c",buttonText:"_1HVhCRI8qehoiWhLWCLL4y",
buttonLabel:"_3DUzAL97qk3vCuZv5ZTGeT"}},function(a,c,f){a.exports={preview:"_1RjnR8nQMSev6CXuRjLUwX",previewBase:"_2nReggaapMZ8dD5AvH4RuB",previewWindow:"QVH7P9eP5Y6QtlKykf0Og"}},function(a,c,f){a.exports={modeLink:"aEVHLv-4Qn_9F0erKQyj3",modeLinkWrapper:"_1ZVbvXUccCD7RJGn9JaTai"}},function(a,c,f){function d(a,b){if(null==a)return{};if(null==a)var e={};else{e={};var h=Object.keys(a),p;for(p=0;p<h.length;p++){var c=h[p];0<=b.indexOf(c)||(e[c]=a[c])}}if(Object.getOwnPropertySymbols)for(p=Object.getOwnPropertySymbols(a),
c=0;c<p.length;c++)h=p[c],0<=b.indexOf(h)||Object.prototype.propertyIsEnumerable.call(a,h)&&(e[h]=a[h]);return e}function k(a){for(var b=1;b<arguments.length;b++){var e=null!=arguments[b]?arguments[b]:{},h=Object.keys(e);"function"===typeof Object.getOwnPropertySymbols&&(h=h.concat(Object.getOwnPropertySymbols(e).filter(function(b){return Object.getOwnPropertyDescriptor(e,b).enumerable})));h.forEach(function(b){l(a,b,e[b])})}return a}function l(a,b,e){b in a?Object.defineProperty(a,b,{value:e,enumerable:!0,
configurable:!0,writable:!0}):a[b]=e;return a}function n(a){if(Array.isArray(a)){var b=0;for(var e=Array(a.length);b<a.length;b++)e[b]=a[b];b=e}else b=void 0;b||(b=Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a)?Array.from(a):void 0);if(!(a=b))throw new TypeError("Invalid attempt to spread non-iterable instance");return a}function w(a){for(var b=1;b<arguments.length;b++){var e=null!=arguments[b]?arguments[b]:{},h=Object.keys(e);"function"===typeof Object.getOwnPropertySymbols&&
(h=h.concat(Object.getOwnPropertySymbols(e).filter(function(b){return Object.getOwnPropertyDescriptor(e,b).enumerable})));h.forEach(function(b){q(a,b,e[b])})}return a}function y(a,b){for(var e=0;e<b.length;e++){var h=b[e];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function ea(a,b,e){b&&y(a.prototype,b);e&&y(a,e);return a}function q(a,b,e){b in a?Object.defineProperty(a,b,{value:e,enumerable:!0,configurable:!0,writable:!0}):a[b]=e;
return a}function E(a,b,e){b in a?Object.defineProperty(a,b,{value:e,enumerable:!0,configurable:!0,writable:!0}):a[b]=e;return a}function F(a){F="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&"function"===typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?"symbol":typeof b};return F(a)}function I(a){for(var b=1;b<arguments.length;b++){var e=null!=arguments[b]?arguments[b]:{},h=Object.keys(e);"function"===typeof Object.getOwnPropertySymbols&&
(h=h.concat(Object.getOwnPropertySymbols(e).filter(function(b){return Object.getOwnPropertyDescriptor(e,b).enumerable})));h.forEach(function(b){v(a,b,e[b])})}return a}function R(a,b){for(var e=0;e<b.length;e++){var h=b[e];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function fa(a,b,e){b&&R(a.prototype,b);e&&R(a,e);return a}function J(a){J=Object.setPrototypeOf?Object.getPrototypeOf:function(b){return b.__proto__||Object.getPrototypeOf(b)};
return J(a)}function r(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return a}function ha(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});b&&K(a,b)}function K(a,b){K=Object.setPrototypeOf||function(b,a){b.__proto__=a;return b};return K(a,b)}function v(a,b,e){b in a?Object.defineProperty(a,
b,{value:e,enumerable:!0,configurable:!0,writable:!0}):a[b]=e;return a}function L(a){L="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&"function"===typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?"symbol":typeof b};return L(a)}function ia(a){for(var b=1;b<arguments.length;b++){var e=null!=arguments[b]?arguments[b]:{},h=Object.keys(e);"function"===typeof Object.getOwnPropertySymbols&&(h=h.concat(Object.getOwnPropertySymbols(e).filter(function(b){return Object.getOwnPropertyDescriptor(e,
b).enumerable})));h.forEach(function(b){z(a,b,e[b])})}return a}function S(a,b){for(var e=0;e<b.length;e++){var h=b[e];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function ja(a,b,e){b&&S(a.prototype,b);e&&S(a,e);return a}function M(a){M=Object.setPrototypeOf?Object.getPrototypeOf:function(b){return b.__proto__||Object.getPrototypeOf(b)};return M(a)}function x(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
return a}function ka(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});b&&N(a,b)}function N(a,b){N=Object.setPrototypeOf||function(b,a){b.__proto__=a;return b};return N(a,b)}function z(a,b,e){b in a?Object.defineProperty(a,b,{value:e,enumerable:!0,configurable:!0,writable:!0}):a[b]=e;return a}function T(a,b){for(var e=0;e<b.length;e++){var h=
b[e];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function la(a,b,e){b&&T(a.prototype,b);e&&T(a,e);return a}function U(a,b,e){b in a?Object.defineProperty(a,b,{value:e,enumerable:!0,configurable:!0,writable:!0}):a[b]=e;return a}function V(a,b){for(var e=0;e<b.length;e++){var h=b[e];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function ma(a,b,e){b&&V(a.prototype,b);e&&
V(a,e);return a}function na(a,b,e){b in a?Object.defineProperty(a,b,{value:e,enumerable:!0,configurable:!0,writable:!0}):a[b]=e;return a}function oa(a){if(Array.isArray(a)){var b=0;for(var e=Array(a.length);b<a.length;b++)e[b]=a[b];b=e}else b=void 0;b||(b=Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a)?Array.from(a):void 0);if(!(a=b))throw new TypeError("Invalid attempt to spread non-iterable instance");return a}function W(a,b){for(var e=0;e<b.length;e++){var h=
b[e];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function pa(a,b,e){b&&W(a.prototype,b);e&&W(a,e);return a}function X(a,b){for(var e=0;e<b.length;e++){var h=b[e];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function qa(a,b,e){b&&X(a.prototype,b);e&&X(a,e);return a}function Y(a,b,e){b in a?Object.defineProperty(a,b,{value:e,enumerable:!0,configurable:!0,writable:!0}):
a[b]=e;return a}function G(a,b,e){b in a?Object.defineProperty(a,b,{value:e,enumerable:!0,configurable:!0,writable:!0}):a[b]=e;return a}function Z(a){for(var b=1;b<arguments.length;b++){var e=null!=arguments[b]?arguments[b]:{},h=Object.keys(e);"function"===typeof Object.getOwnPropertySymbols&&(h=h.concat(Object.getOwnPropertySymbols(e).filter(function(b){return Object.getOwnPropertyDescriptor(e,b).enumerable})));h.forEach(function(b){O(a,b,e[b])})}return a}function O(a,b,e){b in a?Object.defineProperty(a,
b,{value:e,enumerable:!0,configurable:!0,writable:!0}):a[b]=e;return a}function aa(a,b){for(var e=0;e<b.length;e++){var h=b[e];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(a,h.key,h)}}function ra(a,b,e){b&&aa(a.prototype,b);e&&aa(a,e);return a}f.r(c);a=f(0);var t=f.n(a),ba=function(a,b){var e=0;return function(){var h=(new Date).getTime();if(!(h-e<a))return e=h,b.apply(void 0,arguments)}},ca=function(a){return a.dataSet.reduce(function(a,e){e=
Math.max.apply(Math,n(e));return e>a?e:a},0)},sa=function(a){var b=a.data,e=a.scale,h=e*a.layerWidth/(b[b.length-1]-b[0]);return b.reduce(function(a,e,c){e=b[c+1]?a[c]+h*(b[c+1]-e):a[c]+h*(e-b[c-1]);return[].concat(n(a),[Math.floor(100*e)/100])},[-a.offset*e])},ta=function(a){var b=a.xCoords,e=a.layerHeight,h=a.maxValue;return a.data.reduce(function(a,c,d){return[].concat(n(a),[{x:b[d],y:Math.floor(6+(e-e/h*c))}])},[])},ua=function(a){return a.map(function(a){var b=a.columns.reduce(function(a,b){return k({},
a,l({},b[0],b.slice(1)))},{}),h=b.x;b=d(b,["x"]);return k({},a,{x:h,columns:b})})},P=function(a){if(isNaN(a))return a;for(var b=0;1E3<=a;)a/=1E3,b++;return"".concat(a.toPrecision(3)," ").concat(["","K","M","B","T"][b])},Q=function(a){return 1- --a*a*a*a};a=function(){function a(){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");q(this,"layers",{});q(this,"contexts",{});q(this,"touchDevice",!1);q(this,"parent",null);q(this,"parentSize",{});q(this,"dpr",2<(window.devicePixelRatio||
1)?2:window.devicePixelRatio);q(this,"prevState",null);q(this,"tickCount",30);q(this,"iteration",0);q(this,"isInitial",!0);q(this,"animations",{CHART_ANIMATION:[],XAXIS_ANIMATION:[],YAXIS_ANIMATION:[],CHART_SCENE_ANIMATION:[],WINDOW_ANIMATION:[],WINDOW_SCENE_ANIMATION:[]});this.touchDevice="ontouchstart"in document.documentElement}ea(a,[{key:"addAnimationID",value:function(a){this.animations[a.animationID].push(a.id)}},{key:"cancelPrevAnimations",value:function(a){a=a.animationID;var b=this.animations[a].pop();
this.animations[a].map(function(a){return window.cancelAnimationFrame(a)});this.animations[a]=[b]}},{key:"cancelAnimationsByID",value:function(a){a=a.animationID;this.animations[a].map(function(a){return window.cancelAnimationFrame(a)});this.animations[a]=[]}},{key:"cancelAllAnimations",value:function(){var a={},e;for(e in this.animations)this.animations[e].map(function(a){return window.cancelAnimationFrame(a)}),a[e]=[];this.animations=a}},{key:"createLayer",value:function(a){a=a.layerID;var b=document.createElement("canvas");
b.width=this.parentSize.width*this.dpr;b.height=this.parentSize.height*this.dpr;b.style.width="".concat(this.parentSize.width,"px");b.style.height="".concat(this.parentSize.height,"px");var h=b.getContext("2d");h.scale(this.dpr,this.dpr);h.imageSmoothingEnabled=!1;this.layers=w({},this.layers,q({},a,b));this.contexts=w({},this.contexts,q({},a,h));return b}},{key:"getLayerContext",value:function(a){return this.contexts[a.layerID]}},{key:"getLayer",value:function(a){return this.layers[a.layerID]}},
{key:"setLayerSettings",value:function(a){var b=a.settings;if((a=this.getLayerContext({layerID:a.layerID}))&&b)for(var h in b)a[h]=b[h]}},{key:"withHandler",value:function(a){var b=a.handlerType,h=a.handler,c=a.options;c=void 0===c?{}:c;(a=this.getLayer({layerID:a.layerID}))&&a.addEventListener(b,h,c)}},{key:"clearContext",value:function(a){var b=this.width,h=this.height;this.getLayerContext({layerID:a.layerID}).clearRect(0,0,b,h)}},{key:"clearScene",value:function(){var a=this.contexts,e;for(e in a)this.clearContext({layerID:e})}},
{key:"drawChart",value:function(a){var b=a.layerID,h=a.points,c=a.colors;a=a.isInitial;a=void 0===a?!1:a;var d=this.getLayerContext({layerID:b}),f=this.chartHeight,g=this.prevState.points||{},m=Q(this.iteration/this.tickCount);this.clearContext({layerID:b});for(var k in h){d.beginPath();d.strokeStyle=c[k];for(var p=0;p<h[k].length-1;p++){var l=p,u=p+1,n=h[k][l],q=h[k][u];this.preventAnimation?(d.moveTo(n.x,n.y),d.lineTo(q.x,q.y)):a||!g[k]?(d.moveTo(n.x,f-(f*m-n.y*m)),d.lineTo(q.x,f-(f*m-q.y*m))):
g[k][l]&&g[k][u]&&(l=g[k][l],u=g[k][u],d.moveTo(l.x+(n.x-l.x)*m,l.y+(n.y-l.y)*m),d.lineTo(u.x+(q.x-u.x)*m,u.y+(q.y-u.y)*m))}d.lineWidth=2;d.stroke();d.closePath()}this.iteration+=1;this.preventAnimation?this.cancelAnimationsByID({animationID:"CHART_ANIMATION"}):this.iteration<=this.tickCount&&(b=window.requestAnimationFrame(this.drawChart.bind(this,{layerID:b,points:h,colors:c,isInitial:a})),this.addAnimationID({animationID:"CHART_ANIMATION",id:b}))}},{key:"getActiveColumns",value:function(a){var b=
a.activeCharts;a=a.columns;var h={},c;for(c in b)b[c]&&(h[c]=a[c]);return h}},{key:"recalculate",value:function(a){a=a.showFullRange;a=void 0===a?!0:a;var b=this._visibleBounds,h=b.fromIndex,c=b.toIndex;b=b.windowPosition;var d=this._rawData,f=d.columns;d=d.x;var g=this.chartHeight,m=b?b.width:120,p=b?b.x:0;b=this.getActiveColumns({activeCharts:this._activeCharts,columns:f});var n=w({},b);if(c&&!a)for(var B in b)n[B]=f[B].slice(h,c);B=ca({dataSet:Object.values(n)});h=ca({dataSet:Object.values(b)});
c=[];if(!a){c=g-11;g=c/8*(h/B);for(f=[];0<=c;)f.push(Math.floor(100*c)/100),c-=g;c=f}a=sa({layerWidth:this.width,data:d,scale:a?1:this.width/m,offset:a?0:p});d=this.chartHeight;m={};for(u in b)m=k({},m,l({},u,ta({xCoords:a,layerHeight:d,maxValue:B,data:b[u]})));var u=m;this.prevState=this.prevState?w({},this.prevState,{maxInColumns:this.maxInColumns,localMaxInColumns:this.localMaxInColumns,xCoords:this.xCoords,points:this.points,yCoords:this.yCoords}):{maxInColumns:h,localMaxInColumns:B,xCoords:a,
points:u,yCoords:c};this.maxInColumns=h;this.localMaxInColumns=B;this.xCoords=a;this.points=u;this.yCoords=c}},{key:"getCursorPosition",value:function(a){var b=this.parentSize;return this.touchDevice&&a.touches&&a.touches.length?{x:a.touches[0].clientX-b.x,y:a.touches[0].clientY}:{x:a.clientX-b.x,y:a.clientY}}},{key:"setParentSize",value:function(){return this.parentSize=this.parent.getBoundingClientRect()}},{key:"width",get:function(){return this.parentSize.width}},{key:"height",get:function(){return this.parentSize.height}}]);
return a}();c=f(2);var H=f.n(c),A,va=(A={},E(A,"SET_VISIBLE_BOUNDS",function(a,b){a.commit("SET_VISIBLE_BOUNDS",{payload:b.payload,meta:b.meta})}),E(A,"TOGGLE_ACTIVE_CHART",function(a,b){a.commit("TOGGLE_ACTIVE_CHART",{payload:b.payload,meta:b.meta})}),E(A,"TOGGLE_NIGHT_MODE",function(a,b){a.commit("TOGGLE_NIGHT_MODE",{payload:b.payload,meta:b.meta})}),E(A,"TOGGLE_MOOVING_STATE",function(a,b){a.commit("TOGGLE_MOOVING_STATE",{payload:b.payload,meta:b.meta})}),A),wa=function(a){function b(a){var e=
a.parent,c=a.data,d=a.store,f=a.chartID;if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");a=J(b).call(this);a=!a||"object"!==F(a)&&"function"!==typeof a?r(this):a;v(r(a),"borderThreshold",10);v(r(a),"windowPosition",{});v(r(a),"mousePosition",{x:0,y:0});v(r(a),"prevMosuePosition",{x:0,y:0});v(r(a),"mouseDown",!1);v(r(a),"mouseIn",!1);v(r(a),"animationID",null);v(r(a),"transform",null);v(r(a),"hoverType",null);v(r(a),"isMooving",!1);v(r(a),"_delta",0);v(r(a),"moveTimer",
void 0);var g=r(a);g.parent=e;g._rawData=c;g.store=d;g.setParentSize();g.chartHeight=g.parentSize.height;g.chartID=f;g.borderThreshold*=g.dpr;g._visibleBounds=g.store.state.charts[g.chartID].ui.visibleBounds;g._activeCharts=g.store.state.charts[g.chartID].ui.activeCharts;g.nightMode=g.store.state.nightMode;e=g.createLayer({layerID:"WINDOW_LAYER"});c=g.createLayer({layerID:"BASE_LAYER"});e.classList.add(H.a.preview,H.a.previewWindow);c.classList.add(H.a.preview,H.a.previewBase);g.recalculate({showFullRange:!0});
g.setLayerSettings({layerID:"WINDOW_LAYER",settings:{globalCompositeOperation:"destination-over"}});g.windowPosition={x:5,y:0,width:120,height:g.height};g.sliceVisiblePart();g.preventAnimation=!0;g.drawScene();g.touchDevice?(g.withHandler({layerID:"WINDOW_LAYER",handlerType:"touchmove",handler:g.onMouseMove.bind(g),options:{passive:!0}}),g.withHandler({layerID:"WINDOW_LAYER",handlerType:"touchstart",handler:g.onTouchStart.bind(g),options:{passive:!0}}),g.withHandler({layerID:"WINDOW_LAYER",handlerType:"touchend",
handler:g.onTouchEnd.bind(g)}),g.withHandler({layerID:"WINDOW_LAYER",handlerType:"touchcancel",handler:g.onTouchEnd.bind(g)})):(g.withHandler({layerID:"WINDOW_LAYER",handlerType:"mousemove",handler:g.onMouseMove.bind(g)}),g.withHandler({layerID:"WINDOW_LAYER",handlerType:"mouseout",handler:g.onMouseOut.bind(g)}),g.withHandler({layerID:"WINDOW_LAYER",handlerType:"mouseenter",handler:g.onMouseEnter.bind(g)}),g.withHandler({layerID:"WINDOW_LAYER",handlerType:"mousedown",handler:g.onMouseDown.bind(g)}),
g.withHandler({layerID:"WINDOW_LAYER",handlerType:"mouseup",handler:g.onMouseUp.bind(g)}));d.events.subscribe({eventName:"stateChange",callback:g.storeCallback.bind(g)});return a}ha(b,a);fa(b,[{key:"storeCallback",value:function(a){a=a.meta;if(a.id===this.chartID||"ALL"===a.id){this.preventAnimation=this.isInitial=!1;this.iteration=0;this._visibleBounds=this.store.state.charts[this.chartID].ui.visibleBounds;this._activeCharts=this.store.state.charts[this.chartID].ui.activeCharts;this.nightMode=this.store.state.nightMode;
this.recalculate({showFullRange:!0});a=this.store.state.charts[this.chartID].ui.isMooving;this.cancelAllAnimations();var b=window.requestAnimationFrame(this.drawScene.bind(this));this.addAnimationID({animationID:"WINDOW_SCENE_ANIMATION",id:b});this.isMooving=a}}},{key:"drawScene",value:function(){this.drawWindow();this.drawChart({layerID:"BASE_LAYER",points:this.points,colors:this._rawData.colors,isInitial:this.isInitial})}},{key:"setHoverType",value:function(a){a=this.getCursorPosition(a.event);
var b=this.windowPosition,e=this.borderThreshold;return this.hoverType=b.x+b.width-e<=a.x&&a.x<=b.x+b.width+e?"HOVER_RIGHT_BORDER":a.x-e<=b.x&&b.x<=a.x+e?"HOVER_LEFT_BORDER":a.x>b.x&&a.x<b.x+b.width?"HOVER_INNER":null}},{key:"onMouseMove",value:function(a){var b=this.getCursorPosition(a),e=this.mouseDown,c=this.mousePosition,d=this.getLayer({layerID:"WINDOW_LAYER"}),g=this.hoverType;g&&e||(g=this.setHoverType({event:a}));switch(g){case "HOVER_LEFT_BORDER":d.style.cursor="w-resize";this.transform=
"left";break;case "HOVER_RIGHT_BORDER":d.style.cursor="e-resize";this.transform="right";break;case "HOVER_INNER":this.transform=d.style.cursor="move";break;default:d.style.cursor="default",this.transform=null}e&&(this.prevMosuePosition=c,this.mousePosition=b,this.sliceVisiblePart())}},{key:"onMouseDown",value:function(a){a=this.getCursorPosition(a);this.mouseDown=!0;this.mousePosition=this.prevMosuePosition=a;this.toggleMoovingState({isMooving:!0})}},{key:"onTouchStart",value:function(a){this.mouseIn=
!0;this.setHoverType({event:a});this.onMouseDown(a)}},{key:"onTouchEnd",value:function(a){this.mouseIn=!1;this.onMouseUp(a)}},{key:"onMouseUp",value:function(){this.mouseDown=!1;this.toggleMoovingState({isMooving:!1})}},{key:"onMouseEnter",value:function(){this.mouseIn=!0}},{key:"onMouseOut",value:function(){this.mouseDown=this.mouseIn=!1;this.toggleMoovingState({isMooving:!1})}},{key:"drawWindow",value:function(){var a=this.windowPosition,b=this.transform,c=this.delta,d=this.mouseDelta,f=this.nightMode,
g=this.getLayerContext({layerID:"WINDOW_LAYER"}),m=a;this.clearContext({layerID:"WINDOW_LAYER"});"move"===b?m=I({},m,{x:c}):"left"===b?(b=a.width-d,m=I({},m,{x:a.x+d,width:50>b?50:b})):"right"===b&&(b=a.width+d,m=I({},m,{width:50>b?50:b}));this.windowPosition=m;g.strokeStyle=f?"rgba(65, 86, 106, 0.9)":"rgba(221, 234, 243, 0.9)";g.lineWidth=10;g.strokeRect(m.x,m.y,m.width,m.height);g.save();this.drawOverlay()}},{key:"drawOverlay",value:function(){var a=this.width,b=this.height,c=this.windowPosition,
d=this.nightMode,f=this.getLayerContext({layerID:"WINDOW_LAYER"});f.fillStyle=d?"rgba(31, 42, 55, 0.6)":"rgba(245, 249, 251, 0.8)";f.fillRect(c.width+c.x,0,a-c.width,b);f.fillRect(0,0,c.x,b)}},{key:"sliceVisiblePart",value:function(){var a=this.windowPosition,b=this.xCoords,c=this.chartID;this.store.dispatch({actionKey:"SET_VISIBLE_BOUNDS",meta:{id:c},payload:{chartID:c,visibleBounds:{fromIndex:b.findIndex(function(b){return b>=a.x}),toIndex:b.findIndex(function(b){return b>=a.x+a.width}),windowPosition:a}}})}},
{key:"toggleMoovingState",value:function(a){a=a.isMooving;var b=this.store,e=this.chartID;a!==this.isMooving&&b.dispatch({actionKey:"TOGGLE_MOOVING_STATE",meta:{id:e},payload:{chartID:e,isMooving:a}})}},{key:"delta",get:function(){var a=this.windowPosition,b=this.width,c=this._delta+this.mouseDelta;0>=c?c=this._delta:c>=b-a.width&&(c=b-a.width);return this._delta=c}},{key:"mouseDelta",get:function(){return this.mousePosition.x-this.prevMosuePosition.x}}]);return b}(a),xa=function(a){function b(a){var e=
a.parent,c=a.data,d=a.store,f=a.chartID;if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");a=M(b).call(this);a=!a||"object"!==L(a)&&"function"!==typeof a?x(this):a;z(x(a),"_rawData",{});z(x(a),"_visibleBounds",{fromIndex:0,toIndex:0});z(x(a),"_activeIndex",-1);z(x(a),"_mousePosition",{});z(x(a),"_hoverThreshold",10);z(x(a),"_opacity",0);z(x(a),"isMooving",!1);z(x(a),"xAxisIteration",0);z(x(a),"yAxisIteration",0);var g=x(a);g.parent=e;g._rawData=c;g.store=d;g.chartID=
f;g.setParentSize();g.chartHeight=g.parentSize.height-15;e=g.createLayer({layerID:"LINE_CHART_LAYER"});c=g.createLayer({layerID:"X_AXIS_LAYER"});f=g.createLayer({layerID:"LINES_LAYER"});var m=g.createLayer({layerID:"HOVERABLE_LAYER"}),k=g.createLayer({layerID:"TOOLTIP_LAYER"});e.classList.add(t.a.layer);c.classList.add(t.a.layer);f.classList.add(t.a.layer);m.classList.add(t.a.layer);k.classList.add(t.a.layer);g._visibleBounds=d.state.charts[g.chartID].ui.visibleBounds;g._activeCharts=d.state.charts[g.chartID].ui.activeCharts;
g.isInitial=!0;g.setAverageLabelWidth();g.recalculate({showFullRange:!1});g.preventAnimation=!0;g.drawScene();g.touchDevice?(g.withHandler({layerID:"TOOLTIP_LAYER",handlerType:"touchstart",handler:g.onMouseMove.bind(g),options:{passive:!0}}),g.withHandler({layerID:"TOOLTIP_LAYER",handlerType:"touchmove",handler:g.throttledMosueMove.bind(g),options:{passive:!0}}),g.withHandler({layerID:"TOOLTIP_LAYER",handlerType:"touchend",handler:g.hideTooltip.bind(g)})):(g.withHandler({layerID:"TOOLTIP_LAYER",handlerType:"mousemove",
handler:g.throttledMosueMove.bind(g)}),g.withHandler({layerID:"TOOLTIP_LAYER",handlerType:"mouseout",handler:g.hideTooltip.bind(g)}));d.events.subscribe({eventName:"stateChange",callback:g.storeCallback.bind(g)});return a}ka(b,a);ja(b,[{key:"storeCallback",value:function(a){a=a.meta;if(a.id===this.chartID||"ALL"===a.id){this.preventAnimation=this.isInitial=!1;this._visibleBounds=this.store.state.charts[this.chartID].ui.visibleBounds;this._activeCharts=this.store.state.charts[this.chartID].ui.activeCharts;
this.nightMode=this.store.state.nightMode;a=this.store.state.charts[this.chartID].ui.isMooving;this.recalculate({showFullRange:!1});this.yAxisAnimationID=this.xAxisIteration=this.iteration=0;this.cancelAllAnimations();var b=window.requestAnimationFrame(this.drawScene.bind(this));this.addAnimationID({animationID:"CHART_SCENE_ANIMATION",id:b});this.isMooving=a}}},{key:"hideTooltip",value:function(){this.clearContext({layerID:"HOVERABLE_LAYER"});this.clearContext({layerID:"TOOLTIP_LAYER"})}},{key:"dateLabel",
value:function(a){var b=a.additionalOtions;return(new Date(a.UNIXDate)).toLocaleDateString("en-US",ia({month:"short",day:"numeric"},void 0===b?{}:b))}},{key:"drawScene",value:function(){this.clearScene();this.drawChart({layerID:"LINE_CHART_LAYER",points:this.points,colors:this._rawData.colors,isInitial:this.isInitial});this.drawXAxis();this.drawLines()}},{key:"drawXAxis",value:function(){var a=this.chartHeight,b=this.width,c=this.nightMode,d=this.getLayerContext({layerID:"X_AXIS_LAYER"});this.clearContext({layerID:"X_AXIS_LAYER"});
d.strokeStyle=c?"rgb(49, 61, 76)":"rgb(236, 240, 243)";d.beginPath();d.moveTo(0,a-11);d.lineTo(b,a-11);d.stroke();d.fill();d.closePath();d.beginPath();this.drawXAxisTicks();d.closePath()}},{key:"setAverageLabelWidth",value:function(){var a=this.getLayerContext({layerID:"X_AXIS_LAYER"}),b=this._rawData,c=this.dateLabel,d=b.x.reduce(function(e,h,d){h=c({UNIXDate:b.x[d]});h=a.measureText(h);return e+h.width},0)/b.x.length;this._averageLabelWdth=Math.round(d)}},{key:"drawXAxisTicks",value:function(){var a=
this.chartHeight,b=this.width,c=this.xCoords,d=this._rawData,f=this.dateLabel,g=this._averageLabelWdth,m=this.visibleBounds,k=this.nightMode,p=this.prevState,l=this.getLayerContext({layerID:"X_AXIS_LAYER"}),n=m.fromIndex,q=m.toIndex;p=p?p.xCoords:null;m=Q(this.xAxisIteration/this.tickCount);this.clearContext({layerID:"X_AXIS_LAYER"});l.font="lighter ".concat(11,"px Helvetica");l.fillStyle=k?"rgb(85 ,103, 119)":"rgb(150, 162, 170)";b=Math.round(b/(g+40));n=c.slice(n,q);n=Math.round(n.length/b);for(b=
0;b<=c.length;b+=n)g=f({UNIXDate:d.x[b]}),l.fillText(g,this.preventAnimation?c[b]:p[b]+(c[b]-p[b])*m,a);this.xAxisIteration+=1;this.preventAnimation?this.cancelAnimationsByID({animationID:"XAXIS_ANIMATION"}):this.xAxisIteration<=this.tickCount?(a=window.requestAnimationFrame(this.drawXAxisTicks.bind(this)),this.addAnimationID({animationID:"XAXIS_ANIMATION",id:a}),this.cancelPrevAnimations({animationID:"XAXIS_ANIMATION"})):this.xAxisIteration=0}},{key:"drawLines",value:function(){var a=this.width,
b=this.nightMode,c=this.maxInColumns,d=this.localMaxInColumns,f=this.yCoords,g=this.prevState.yCoords,m=this.getLayerContext({layerID:"LINES_LAYER"}),k=Q(this.yAxisIteration/this.tickCount);d=d/8*(c/d);this.clearContext({layerID:"LINES_LAYER"});m.strokeStyle=b?"rgb(41, 53, 67)":"rgb(242, 244, 245)";m.fillStyle=b?"rgb(85 ,103, 119)":"rgb(150, 162, 170)";m.font="lighter ".concat(9,"px Helvetica");m.beginPath();b=0;for(var p=c,l=0;l<=f.length;l++){var n=g[l]?g[l]+(f[l]-g[l])*k:f[l]*k;this.preventAnimation&&
(n=f[l]);m.moveTo(0,n);m.lineTo(a,n);m.fillText(b?P(b):0,0,n-7);p-=d;b=c-p}m.stroke();m.closePath();this.yAxisIteration+=1;this.preventAnimation?this.cancelAnimationsByID({animationID:"YAXIS_ANIMATION"}):this.yAxisIteration<=this.tickCount?(a=window.requestAnimationFrame(this.drawLines.bind(this)),this.addAnimationID({animationID:"YAXIS_ANIMATION",id:a}),this.cancelPrevAnimations({animationID:"YAXIS_ANIMATION"})):this.yAxisIteration=0}},{key:"onMouseMove",value:function(a){var b=this.getCursorPosition(a);
a=this.xCoords;var e=this._hoverThreshold;this._mousePosition=b;this._activeIndex=a.findIndex(function(a){return b.x>=a-e&&b.x<=a+e?!0:!1});window.requestAnimationFrame(this.drawOnHover.bind(this))}},{key:"drawOnHover",value:function(){var a=this._activeIndex,b=this.xCoords,c=this.chartHeight,d=this._rawData,f=this.points,g=this.nightMode,m=this.getLayerContext({layerID:"HOVERABLE_LAYER"});d=d.colors;this.clearContext({layerID:"HOVERABLE_LAYER"});if(-1<a){b=b[a];m.fillStyle=g?"rgb(36, 47, 61)":"rgb(255, 255, 255)";
m.strokeStyle=g?"rgb(60, 74, 89)":"rgb(223, 230, 235)";m.beginPath();m.lineWidth=1;m.moveTo(b,0);m.lineTo(b,c-11);m.stroke();m.closePath();for(var k in f)c=f[k][a].y,m.strokeStyle=d[k],m.lineWidth=4,m.beginPath(),m.arc(b,c,4,0,2*Math.PI),m.stroke(),m.fill(),m.closePath()}this.drawTooltip()}},{key:"calculateTooltipWidth",value:function(){var a=this.getLayerContext({layerID:"TOOLTIP_LAYER"}),b=this._activeIndex,c=this._activeCharts,d=this._rawData.columns,f=0,g=0,m;for(m in d)if(c[m]){var k=P(d[m][b]);
f+=a.measureText(k).width;g++}a=Math.round(f)+5*(g+1);return 100>a?100:a}},{key:"drawRoundRect",value:function(a){var b=a.context,e=a.x,c=a.y,d=a.width;a=a.height;var g=this.nightMode;b.beginPath();b.lineWidth=1;b.moveTo(e+6,c);b.lineTo(e+d-6,c);b.quadraticCurveTo(e+d,c,e+d,c+6);b.lineTo(e+d,c+a-6);b.quadraticCurveTo(e+d,c+a,e+d-6,c+a);b.lineTo(e+6,c+a);b.quadraticCurveTo(e,c+a,e,c+a-6);b.lineTo(e,c+6);b.quadraticCurveTo(e,c,e+6,c);b.fillStyle=g?"rgb(37, 50, 64)":"rgb(255, 255, 255)";b.strokeStyle=
g?"rgb(32, 42, 54)":"rgb(227, 227, 227)";b.fill();b.stroke();b.closePath()}},{key:"drawTooltipText",value:function(a){var b=a.context,c=a.date,e=a.x;a=a.y;var d=this._activeIndex,g=this._rawData,f=this.nightMode,k=this._activeCharts;b.font="lighter 15px Helvetica";b.fillStyle=f?"rgb(255, 255, 255)":"rgb(34, 34, 34)";b.fillText(c,e+5,a+25);b.save();c=5;for(var l in g.columns)if(k[l]){b.fillStyle=g.colors[l];f=P(g.columns[l][d]);var p=g.names[l];b.fillText(f,e+c,a+50);b.fillText(p,e+c,a+70);c=c+b.measureText(f).width+
5;b.save()}}},{key:"drawTooltip",value:function(){var a=this.getLayerContext({layerID:"TOOLTIP_LAYER"}),b=this._activeIndex,c=this._rawData,d=this.dateLabel,f=this.width,g=this.xCoords[b]+20;this.clearContext({layerID:"TOOLTIP_LAYER"});if(-1<b){var k=this.calculateTooltipWidth();b=d({UNIXDate:c.x[b],additionalOtions:{weekday:"short"}});g+k>f&&(g-=k+40);this.drawRoundRect({context:a,x:g,y:20,width:k,height:80});this.drawTooltipText({context:a,date:b,x:g,y:20})}}},{key:"visibleBounds",get:function(){return this._visibleBounds}},
{key:"rawData",get:function(){return this._rawData}},{key:"throttledMosueMove",get:function(){return ba(10,this.onMouseMove.bind(this))}}]);return b}(a);A=f(1);var C=f.n(A),ya=function(){function a(b){var c=b.store,d=b.id;b=b.chartID;if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");U(this,"_active",!0);U(this,"_id",void 0);this._id=d;this.store=c;this.chartID=b;this.buttonWrapper=document.createElement("div");this.buttonWrapper.classList.add(C.a.buttonWrapper);this.buttonWrapper.classList.add(t.a.buttonWrapper);
this.buttonWrapper.classList.add(C.a.active);c=document.createElement("div");b=document.createElementNS("http://www.w3.org/2000/svg","svg");var f=document.createElementNS("http://www.w3.org/2000/svg","circle"),k=document.createElementNS("http://www.w3.org/2000/svg","path");b.classList.add(C.a.buttonLabel);f.classList.add(C.a.buttonLabelCircle);k.classList.add(C.a.buttonLabelIcon);b.setAttribute("viewBox","0 0 52 52");f.setAttribute("cx",26);f.setAttribute("cy",26);f.setAttribute("r",24);f.setAttribute("stroke",
this.store.state.charts[this.chartID].orm.data.colors[d]);f.setAttribute("fill",this.store.state.charts[this.chartID].orm.data.colors[d]);k.setAttribute("d","M14.1 27.2l7.1 7.2 16.7-16.8");b.appendChild(f);b.appendChild(k);c.classList.add(C.a.buttonText);c.innerText=this.store.state.charts[this.chartID].orm.data.names[d];this.buttonWrapper.appendChild(b);this.buttonWrapper.appendChild(c);this.buttonWrapper.addEventListener("click",this.throttledClickHandler.bind(this))}la(a,[{key:"clickHandler",value:function(a){a.preventDefault();
this.buttonWrapper.classList.toggle(C.a.active);this._active=!this._active;this.store.dispatch({actionKey:"TOGGLE_ACTIVE_CHART",meta:{id:this.chartID},payload:{chartID:this.chartID,id:this._id,state:this._active}})}},{key:"throttledClickHandler",get:function(){return ba(500,this.clickHandler.bind(this))}}]);return a}();A=f(3);var da=f.n(A),za=function(){function a(b){var c=b.store,d=b.wrapper;if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");na(this,"nightMode",!1);
var f=this,k=document.createElement("div");f.modeLinkWrapper=document.createElement("div");f.modeLinkWrapper.classList.add(da.a.modeLinkWrapper);f.modeLinkWrapper.classList.add(t.a.modeLinkWrapper);k.classList.add(da.a.modeLink);k.classList.add(t.a.modeLink);k.innerHTML=f.modeText;f.modeLinkWrapper.appendChild(k);f.modeLinkWrapper.addEventListener("click",function(){d.classList.toggle(t.a.nightMode);f.nightMode=!f.nightMode;k.innerHTML=f.modeText;c.dispatch({actionKey:"TOGGLE_NIGHT_MODE",meta:{id:"ALL"},
payload:{nightMode:f.nightMode}})})}ma(a,[{key:"mode",get:function(){return this.nightMode?"Day":"Night"}},{key:"modeText",get:function(){return"Switch to ".concat(this.mode," Mode")}}]);return a}(),Aa=function(){function a(){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");this.events=new Map}pa(a,[{key:"subscribe",value:function(a){var b=a.eventName;a=a.callback;var c=this.events;c.has(b)||c.set(b,[]);c.set(b,[].concat(oa(c.get(b)),[a]))}},{key:"publish",value:function(a){var b=
a.eventName,c=a.data,d=void 0===c?{}:c;a=a.meta;var f=void 0===a?{}:a;a=this.events;return a.has(b)?a.get(b).map(function(a){return a({data:d,meta:f})}):[]}}]);return a}(),Ba=function(){function a(b){var c=b.actions;c=void 0===c?{}:c;var d=b.mutations;d=void 0===d?{}:d;b=b.state;b=void 0===b?{}:b;if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");Y(this,"actions",{});Y(this,"mutations",{});this.events=new Aa;this.actions=c;this.mutations=d;this.state=b}qa(a,[{key:"dispatch",
value:function(a){var b=this.actions[a.actionKey];return b?b(this,{payload:a.payload,meta:a.meta}):!1}},{key:"commit",value:function(a,c){var b=c.meta;a=this.mutations[a];if(!a)return!1;c=Object.assign(this.state,a(this.state,{payload:c.payload,meta:b}));this.events.publish({eventName:"stateChange",data:c,meta:b});return c}}]);return a}(),D,Ca=(D={},G(D,"SET_VISIBLE_BOUNDS",function(a,b){b=b.payload;a.charts[b.chartID].ui.visibleBounds=b.visibleBounds;return a}),G(D,"TOGGLE_ACTIVE_CHART",function(a,
b){b=b.payload;a.charts[b.chartID].ui.activeCharts[b.id]=b.state;return a}),G(D,"TOGGLE_NIGHT_MODE",function(a,b){a.nightMode=b.payload.nightMode;return a}),G(D,"TOGGLE_MOOVING_STATE",function(a,b){b=b.payload;a.charts[b.chartID].ui.isMooving=b.isMooving;return a}),D);new (function(){function a(b){b=b.data;if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");this.data=ua(b);this.store=this.initializeStore({data:this.data,rawData:b});this.appContainter=document.getElementById("app");
this.wrapperContainer=document.getElementById("wrapper");this.data.map(this.throttledInit.bind(this));b=new za({store:this.store,wrapper:this.wrapperContainer});this.appContainter.appendChild(b.modeLinkWrapper)}ra(a,[{key:"throttledInit",value:function(a,c){this.initializeChart.bind(this,{chartData:a,store:this.store,index:c,chartID:"CHART_ID_".concat(c)})()}},{key:"initializeStore",value:function(a){var b=a.data,c=a.rawData;a=b.reduce(function(a,d,e){d=Object.keys(d.columns).reduce(function(a,b){return Z({},
a,O({},b,!0))},{});return Z({},a,O({},"CHART_ID_".concat(e),{ui:{visibleBounds:{},activeCharts:d},orm:{_rawData:c[e],data:b[e]}}))},{});return new Ba({actions:va,mutations:Ca,state:{nightMode:!1,charts:a}})}},{key:"initializeChart",value:function(a){var b=a.chartData,c=a.store,d=a.index,f=a.chartID,k=this.appContainter;a=document.createElement("div");var g=document.createElement("h2"),m=document.createElement("div"),l=document.createElement("div"),n=document.createElement("div");g.classList.add(t.a.chartTitle);
g.innerHTML="Graph # ".concat(d+1);k.appendChild(a);a.appendChild(g);a.appendChild(l);a.appendChild(m);a.classList.add(t.a.chartContainer);m.classList.add(t.a.previewWrapper);l.classList.add(t.a.chartWrapper);n.classList.add(t.a.buttonsWrapper);d=new wa({parent:m,store:c,data:b,chartID:f});k=new xa({parent:l,store:c,data:b,chartID:f});l.appendChild(k.getLayer({layerID:"X_AXIS_LAYER"}));l.appendChild(k.getLayer({layerID:"LINES_LAYER"}));l.appendChild(k.getLayer({layerID:"LINE_CHART_LAYER"}));l.appendChild(k.getLayer({layerID:"HOVERABLE_LAYER"}));
l.appendChild(k.getLayer({layerID:"TOOLTIP_LAYER"}));m.appendChild(d.getLayer({layerID:"BASE_LAYER"}));m.appendChild(d.getLayer({layerID:"WINDOW_LAYER"}));Object.keys(b.names).map(function(a){a=new ya({store:c,id:a,chartID:f});n.appendChild(a.buttonWrapper);return a});a.appendChild(n)}}]);return a}())({data:window.data})}]);}).call(this || window)
