export const BASE_LAYER = 'BASE_LAYER';
export const WINDOW_LAYER = 'WINDOW_LAYER';
export const BACKGROUND_LAYER = 'BACKGROUND_LAYER';

export const HOVER_INNER = 'HOVER_INNER';
export const HOVER_LEFT_BORDER = 'HOVER_LEFT_BORDER';
export const HOVER_RIGHT_BORDER = 'HOVER_RIGHT_BORDER';
